name: auto_reflect
description: Automatic Git work log generator with AI analysis.
version: 1.0.6+17

environment:
  sdk: ^3.5.4

executables:
  journal: auto_reflect

dependencies:
  args: ^2.6.0
  cli_spin: ^1.0.1
  http: ^1.2.2
  openai_dart: ^0.4.5
  package_info_plus: ^8.1.1
  process_run: ^1.2.2
  yaml: ^3.1.2
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.0